// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4f9EyCMO9YUZjf6PXp9c2G40mAN-DqbI',
    appId: '1:122790787691:web:c6775d0abc5fdc3188cf2e',
    messagingSenderId: '122790787691',
    projectId: 'to-do-app-flutter-ca61c',
    authDomain: 'to-do-app-flutter-ca61c.firebaseapp.com',
    storageBucket: 'to-do-app-flutter-ca61c.appspot.com',
    measurementId: 'G-C6Y2B2SRFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Zb2WaK3-H8YWShmCaIH5at6IqnSjTWQ',
    appId: '1:122790787691:android:04239b0b3544076b88cf2e',
    messagingSenderId: '122790787691',
    projectId: 'to-do-app-flutter-ca61c',
    storageBucket: 'to-do-app-flutter-ca61c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDniOgvy9CezValNU8M1nG-bVCSzUlih8s',
    appId: '1:122790787691:ios:c33f20252412fde588cf2e',
    messagingSenderId: '122790787691',
    projectId: 'to-do-app-flutter-ca61c',
    storageBucket: 'to-do-app-flutter-ca61c.appspot.com',
    iosBundleId: 'com.example.todoApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDniOgvy9CezValNU8M1nG-bVCSzUlih8s',
    appId: '1:122790787691:ios:c33f20252412fde588cf2e',
    messagingSenderId: '122790787691',
    projectId: 'to-do-app-flutter-ca61c',
    storageBucket: 'to-do-app-flutter-ca61c.appspot.com',
    iosBundleId: 'com.example.todoApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4f9EyCMO9YUZjf6PXp9c2G40mAN-DqbI',
    appId: '1:122790787691:web:07372de5b57b6ee688cf2e',
    messagingSenderId: '122790787691',
    projectId: 'to-do-app-flutter-ca61c',
    authDomain: 'to-do-app-flutter-ca61c.firebaseapp.com',
    storageBucket: 'to-do-app-flutter-ca61c.appspot.com',
    measurementId: 'G-BPPFNL3VL0',
  );
}
